apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-m2-deployment
  labels:
    app: backend-m2-deployment
spec:
  selector:
    matchLabels:
      app: backend-m2-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-m2-deployment
    spec:
      containers:
        - name: backend-m2
          image: klefurusach/backend-m2:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://backend-config:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://backend-eureka:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_CUOTA
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_CUOTA
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-m2
  labels:
    app: backend-m2
spec:
  selector:
    app: backend-m2-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer